[package]
name = "usbsas-scsi"
version = "0.1.2"
edition = "2021"
license = "GPL-3.0"

[dependencies]
byteorder = "1.5"
log = "0.4"
rusb = { git = "https://github.com/losynix/rusb", branch = "disable_device_discovery", features = ["vendored"] }
