[package]
name = "usbsas-net"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
base64 = { version = "0.13.0", optional = true }
env_logger = "0.9.0"
libgssapi = { version = "0.6.3", optional = true }
log = "0.4.17"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.143", features = ["derive"] }
thiserror = "1.0.32"
usbsas-comm = { path = "../usbsas-comm" }
usbsas-config = { path = "../usbsas-config" }
usbsas-process = { path = "../usbsas-process" }
usbsas-proto = { path = "../usbsas-proto" }
usbsas-utils = { path = "../usbsas-utils", optional = true }

[features]
authkrb = ["base64", "libgssapi"]
default = ["authkrb"]
