[package]
name = "usbsas-utils"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
env_logger = "0.9.0"
log = "0.4.17"
serde_json = { version = "1.0.83", optional = true }
thiserror = { version = "1.0.32", optional = true }
time = { version = "0.3.13", features = ["formatting"], optional = true }

[features]
log-json = ["serde_json", "time"]
