[package]
name = "usbsas-analyzer-server"
description = "usbsas analyzer server (with clamav)"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
actix-web = "4.2.1"
clamav-rs = "0.5.5"
env_logger = "0.9.1"
futures = "0.3.24"
log = "0.4.17"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.85"
tar = "0.4.38"
tempfile = "3.3.0"
uuid = { version = "1.1.2", features = ["v4"] }

# cargo-deb
[package.metadata.deb]
maintainer = "usbsas"
copyright = "usbsas"
depends = "$auto, usbsas-server, clamav-freshclam"
section = "utility"
priority = "optional"
maintainer-scripts = "debian/"
systemd-units = { enable = false }
assets = [
  ["target/release/usbsas-analyzer-server", "usr/bin/", "755"],
]
