[package]
name = "usbsas-config"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
lazy_static = "1.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.6"
